#!/bin/bash
set -e

docker-compose -f server/config/docker/development.yml stop
docker-compose -f server/config/docker/development.yml rm -f
docker-compose -f server/config/docker/development.yml pull
pushd server &> /dev/null
npm install
popd &> /dev/null

# TODO: add admin init
