#!/bin/bash
set -e

docker-compose -f server/config/docker/development.yml stop
docker-compose -f server/config/docker/development.yml rm -f
docker-compose -f server/config/docker/development.yml pull
scripts/install
