#!/bin/bash
set -e

################################################################################
# variables                                                                    #
################################################################################
DOCKER_IMAGE_NAME=dylanfoster/bonfire
TAG=$1

################################################################################
# functions                                                                    #
################################################################################
log(){
  echo -e "$1";
}

info() {
  log "\033[1;32m==> $@\033[0m";
}

success() {
  log "\033[0;32m✔ $@\033[0m";
}

error() {
  log "\033[1;31m✖ $@\033[0m";
}

clean() {
  scripts/clean
}

docker_build () {
  docker build -t dylanfoster/bonfire .
}

docker_push() {
  local tags=("latest" "$TAG")

  for tag in ${tags[@]}; do
    docker push $DOCKER_IMAGE_NAME:$tag
  done
}

docker_tag() {
  local tags=("latest" "$TAG")

  for tag in ${tags[@]}; do
    docker tag -f $DOCKER_IMAGE_NAME:latest \
      $DOCKER_IMAGE_NAME:$tag
  done
}

git_release() {
  git release $TAG
}

install_dependencies() {
  scripts/install
}

require_version() {
  if [ -z "$TAG" ]; then
    error "please specify a version"
    exit 1
  fi
}

require_version
clean
install_dependencies
docker_build
docker_tag
