#!/bin/bash
set -e

################################################################################
# variables                                                                    #
################################################################################
DOCKER_IMAGE_NAME=dylanfoster/bonfire
TAG=$1

################################################################################
# functions                                                                    #
################################################################################
log(){
  echo -e "$1";
}

info() {
  log "\033[1;32m==> $@\033[0m";
}

success() {
  log "\033[0;32m✔ $@\033[0m";
}

error() {
  log "\033[1;31m✖ $@\033[0m";
}

build_admin_app() {
  pushd admin &> /dev/null
  install_npm
  install_bower
  build_ember --environment production
  popd &> /dev/null
}

build_ember() {
  ember build $@
}

build_api() {
  pushd server &> /dev/null
  install_npm
  popd &> /dev/null
}

clean() {
  scripts/clean
}

docker_build () {
  docker build -t dylanfoster/bonfire .
}

docker_push() {
  local tags=("latest" "$TAG")

  for tag in ${tags[@]}; do
    docker push $DOCKER_IMAGE_NAME:$tag
  done
}

docker_tag() {
  local tags=("latest" "$TAG")

  for tag in ${tags[@]}; do
    docker tag -f $DOCKER_IMAGE_NAME:latest \
      $DOCKER_IMAGE_NAME:$tag
  done
}

git_release() {
  git release $TAG
}

install_bower() {
  bower install --allow-root
}

install_npm() {
  npm install
}

require_version() {
  if [ -z "$TAG" ]; then
    error "please specify a version"
    exit 1
  fi
}

require_version
clean
build_admin_app
build_api
docker_build
docker_tag
docker_push
git_release
