---

npm:
  container_name: bonfire_development_npm
  extends:
    file: common.yml
    service: ember
  entrypoint: ["/usr/bin/npm"]

bower:
  container_name: bonfire_development_bower
  extends:
    file: common.yml
    service: ember
  entrypoint: ["/usr/bin/bower", "--allow-root"]

server:
  container_name: bonfire_development_ember
  extends:
    file: common.yml
    service: ember
  ports:
    - "4200:4200"
    - "35729:35729"
